### ISSUE TITLE
NiMARE Meta-Analysis Documentation & Tutorials

### ISSUE THREAD

**Issue by jdkent** [jdkent/hackathon2022#1]
### Title

NiMARE Meta-Analysis Documentation & Tutorials

### Short description and the goals for the OHBM BrainHack

Currently, there is a mix of methods descriptions (the [NiMARE Methods](https://nimare.readthedocs.io/en/latest/methods.html) page) and [examples](https://nimare.readthedocs.io/en/latest/auto_examples/index.html) of NiMARE's functionality, but those two elements are very separate, and the examples are more a smattering of disconnected exhibitions than a tutorial.

We came up with the idea of making the documentation more into a user guide.

## Resources
- https://nimare.readthedocs.io/en/latest/methods.html
- https://nimare.readthedocs.io/en/latest/auto_examples/index.html
- https://github.com/neurostuff/ohbm2021-nimare-tutorial
- https://github.com/NBCLab/nimare-paper

## Goals
- [ ] Create a jupyter book
  - [ ] Leverage existing resources (see above)
  - [ ] Write tutorial documentation with a novice meta-analysis practicitioner in mind
- [ ] Have people test jupyter book for typos/understanding/correctness

### Link to the Project

https://github.com/neurostuff/nimare-book

### Image for the OHBM brainhack website

https://nimare.readthedocs.io/en/latest/_images/nimare_overview.png

### Project lead

James Kent, github:@jdkent, discord:@jdkent#4667

### Main Hub

Glasgow

### Other Hub covered by the leaders

- [ ] Glasgow
- [ ] Asia / Pacific
- [ ] Europe / Middle East / Africa
- [ ] Americas

### Skills

Minimally, one of the following:
- meta-analysis: beginner
- python: beginner

### Recommended tutorials for new contributors

- [X] [Set up a brainhack friendly computing environment](https://psy6983.brainhackmtl.org/modules/installation/)
- [ ] [A introduction to Bash](https://psy6983.brainhackmtl.org/modules/introduction_to_terminal/)
- [ ] [Python: Writing a script](https://psy6983.brainhackmtl.org/modules/python_scripts/)
- [X] [Python: Data analysis with Python](https://psy6983.brainhackmtl.org/modules/python_data_analysis/)
- [ ] [Python: Visualisation](https://psy6983.brainhackmtl.org/modules/python_visualization/)
- [ ] [Machine learning basics](https://psy6983.brainhackmtl.org/modules/machine_learning_basics/)
- [ ] [BIDS](https://psy6983.brainhackmtl.org/modules/bids/)
- [ ] [Machine learning for neuroimaging](https://psy6983.brainhackmtl.org/modules/machine_learning_neuroimaging/)
- [X] [VCS: Using Git and Github](https://psy6983.brainhackmtl.org/modules/git_github/)
- [ ] [VCS: Data management with Datalad](https://psy6983.brainhackmtl.org/modules/datalad/)
- [ ] [Virtualization](https://psy6983.brainhackmtl.org/modules/containers/)
- [ ] High Performance Computing: [Oracle cloud resource](https://brainhack.org/brainhack_cloud/)

### Good first issues

- testing the existing resources listed above
- testing iterations of the book once it is created

### Twitter summary

Interested in making neuroimaging meta-analyses more accessible and easier to understand?
Help us make a guide for neuroimaging meta-analysis using NiMARE, a fantastic python library
covering many of the meta-analytic algorithms published to date.

### Short name for the Discord chat channel (~15 chars)

nimare-user-guide

### Please read and follow the OHBM Code of Conduct

- [X] I agree to follow the OHBM Code of Conduct during the hackathon
